language: java
jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - docker build -t thrust-v4 ci/

script: docker run -v $(pwd):/app thrust-v4  /bin/sh -c "cd app/test && thrust install && thrust test.js"